### ISSUE TITLE
Socket symlink creation fails

### ISSUE THREAD

**Issue by pcouy** [leomos/dwgd#2]
When using the provided `dwgd.service` file, the plugin does not start with the following message from `journalctl -xe -u dwgd` : 

```
Couldn't initialize plugin: symlink /run/dwgd/dwgd.sock /run/docker/plugins/dwgd.sock: no such file or directory
```

This seems to be due to the fact that the plugin is started before the docker daemon, which expects the `/run/docker/plugins/` directory to exist. This prevents containers using `dwgd` as a network driver from automatically starting at boot.

**Comment by leomos** [comment]
Hello @pcouy, thanks for reporting this. 
You are right that's exactly what happens, the directory doesn't exists and it fails, but that's on purpose.

What were the circumstances on your machine that led to this?
For example, did you install `dwgd`, restarted your PC and that happened?

As a more general note there are a few of points to address this though:
1. Should `dwgd` run when `docker` is not running?
In my mind there is no reason why `dwgd` should run when `docker` is not running.
Since `dwgd` is an extension of `docker` and nothing more, if the `docker` service is not running neither should `dwgd`.
Do you have any use case where `dwgd` should outlive `docker`?

2. If we agree on point 1, we can also agree that your solution (albeit probably working!) is not really solving the problem.
With the modifications in your PR, `dwgd` would start even if `docker` isn't running, what would that achieve?
Also what happens when `docker` starts to the `/run/docker` directory? Does `docker` starts populating it or does it remove it and create a new one? If it starts populating it without touching the `.sock` file, we cannot ensure that a new docker update keeps this behavior.
Last but not least, the directory would be created with the user that's actually running `dwgd` and not `docker` and we cannot assume that they are the same or they have overlapping permissions.
Doing what you propose in the PR we are essentially overstepping boundaries and entering "too much" into `docker` own implementation and responsabilities...honestly even writing into the `/run/docker/plugins` directory is probably too much, but I couldn't find any other way 😄 .

3. How do we ensure that `dwgd` does not outlive `docker`?
This is not an easy one, but since `dwgd` only supports `systemd` for now, we can probably use the [`BindsTo=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#BindsTo=) directive.
I also noticed that these lines  https://github.com/leomos/dwgd/blob/main/init/dwgd.service#L3-L5:
    ```
    Before=docker.service
    After=network.target
    Requires=docker.service
    ```
    do not make much sense.

Solution wise I think we should change the `.service` file to something like:
```
[Unit]
Description=dwgd
After=network.target
Requires=docker.service
BindsTo=docker.service
```
and leave the Go source code as it is, but I haven't tested it, so take it with a grain of salt.

If you can/want to test this change and send another PR that'd be awesome!

**Comment by pcouy** [comment]
This is a short answer since it's getting late in my timezone. Let me know if more details are needed. 

I'm using dwgd in containers with the `restart: always` option, which starts my containers as soon as the docker daemon starts.

After reading [Docker's documentation on plugins lifecycle](https://docs.docker.com/engine/extend/plugin_api/#plugin-lifecycle), I think dwgd should outlive docker. The reason the documentation mentions this is probably so that plugins are available to containers that are auto started with docker.

**Comment by leomos** [comment]
You are absolutely right! I guess I should have trusted my old self more 😅 .

I tried a few combinations of restarting/disabling the `docker` service and the `dwgd` service but couldn't consistently reproduce the bug unless I uninstall docker completely.

What are the circumstances in which that happens for you?

**Comment by pcouy** [comment]
This happens when the docker daemon first starts at boot. 

I'm not at my computer to try stuff right now, but maybe the `/run/docker/plugins/` directory gets deleted on reboot? (and is recreated when docker starts)

I also tried playing with systemd unit dependencies like you suggested before submitting the PR, but I did not manage to come up with another solution

**Comment by leomos** [comment]
Yes `/run/docker/plugins` probably gets deleted and recreated (usually `/run` is mounted as `tmpfs` so it doesn't "survive" reboots).
What Linux distro and what docker version are you working on?

**Comment by pcouy** [comment]
I'm running Ubuntu server 22.04 (LTS) with the official repository's docker package.

Anyway, according to Docker's documentation, the plugin should make the socket available before docker starts, which seems to imply creating the directory if it does not already exist. This is what [Docker official plugin helpers](https://github.com/docker/go-plugins-helpers/blob/6eecb7beb65124bb44a23848bb46e98b4f50ae18/sdk/unix_listener.go#L27) do.

**Comment by leomos** [comment]
indeed, thanks for checking that.
I'm still not convinced about the whole "which user creates the directory" situation, but your PR does what it should.
I will add a comment on the PR now.
